CREATE TABLE cities (
id BIGSERIAL primary key, 
city_name TEXT NOT NULL,
lat DECIMAL(9,6),
lng DECIMAL(9,6),
created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


