CREATE TABLE waste_type (
id BIGSERIAL PRIMARY KEY,
collecte_id BIGINT REFERENCES collects(id) ON DELETE SET NULL,
type waste_enum NOT NULL,
quantity INTEGER DEFAULT 0,
created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
); 