CREATE TABLE collects (
id BIGSERIAL PRIMARY KEY,
date DATE NOT NULL,
city TEXT NOT NULL,
volunteer_id BIGINT,
FOREIGN KEY (volunteer_id) REFERENCES volunteers(id) ON DELETE SET NULL,
city_id BIGINT, 
FOREIGN KEY (city_id) REFERENCES cities(id) ON DELETE SET NULL,
created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);